sudo: required

services:
  - docker 

# Caching so the next build will be fast too.
cache:
  timeout: 600
  bundler: true
  directories:
  - $HOME/.stack
  - $HOME/build/peterbecich/stock-common/.stack-work
  #- /var/lib/docker
  - $HOME/docker  #https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326

before_install:
  - df -h
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

  - eval "$(ssh-agent -s)" #start the ssh agent

  - openssl aes-256-cbc -K $encrypted_6c7819373136_key -iv $encrypted_6c7819373136_iv -in travis_common_secrets.tar.enc -out travis_common_secrets.tar -d
  - tar xvf travis_common_secrets.tar

  - chmod 600 travis_common
  - ssh-add travis_common

  - chmod 600 travis_common_push_github
  - ssh-add travis_common_push_github
  
  - docker pull fpco/stack-build:lts-9.17
  
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup

  - df -h

# install:
#   - git clone git@github.com:${TRAVIS_REPO_SLUG}.git $TRAVIS_REPO_SLUG
#   - cd $TRAVIS_REPO_SLUG
#   - git checkout -qf $TRAVIS_COMMIT
  
script:
  - df -h
  - stack build
  - stack image container
  - df -h

# https://gist.github.com/petrbel/c3bf7e0f59c22a52f534
git:
  submodules: false
  
after_success:
  
  - echo "success; run merge_script.sh"
  - ./scripts/merge_script.sh

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
