
resolver: lts-9.13

packages:
- .

extra-deps: [yaml-config-0.4.0]

flags: {}

extra-package-dbs: []

ghc-options:
  "*": -j -threaded


docker:
  enable: true

image:
  containers:
    -
      base: "fpco/stack-build:lts-9.13"
      name: "peterbecich/stock-common"

      add:
        conf/: /usr/local/etc/
