
# resolver: lts-9.17
resolver: lts-10.3

packages:
- .

extra-deps: [yaml-config-0.4.0]

flags: {}

extra-package-dbs: []

# ghc-options:
#   "*": -j -threaded


docker:
  enable: true

image:
  containers:
    -
      # base: "fpco/stack-build:lts-9.17"
      base: "fpco/stack-build:lts-10.3"
      name: "peterbecich/stock-common"

      add:
        conf/: /usr/local/etc/
        data/: /usr/local/data/
      entrypoints:
        - load-stocks
      executables:
        - load-stocks
