# https://gist.github.com/dbp/bef96402ea07001dfed2
# https://circleci.com/docs/2.0/hello-world/
# https://circleci.com/docs/1.0/config-sample/

version: 2
jobs:
   build:
     docker:
       - image: circleci/build-image:latest
     steps:
       - checkout
       - run: echo "hello world"
