# https://gist.github.com/dbp/bef96402ea07001dfed2
# https://circleci.com/docs/2.0/hello-world/
# https://circleci.com/docs/2.0/configuration-reference/
# https://hub.docker.com/_/haskell/
version: 2
jobs:
   build:
     docker:
       - image: haskell:latest
       #- image: ubuntu:14.04
     steps:
       - checkout
       - run: sudo apt-get install xz-utils make
       - run: stack setup --no-terminal
       - run: stack build --only-configure --no-terminal
